### ISSUE TITLE
閲覧者用の画面を作成

### ISSUE THREAD

**Issue by kinoshita0923** [NIT-Anan-Procon/procon33_RemoteTravelers_app#11]
## 概要
閲覧者用の画面を作成

## 具体的にやること

- [x] #12
- [x] APIをたたき、必要なデータを取得
- [x] 取得したデータを表示

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/7eHbwS6kRyybebRecWNSiY/RemoteTravelers?node-id=139%3A78

## ゴール・目的（完成物の定義）
閲覧者画面に必要な機能を実装できている状態

**Comment by Mitsuki4123** [comment]
別issueで対応
