### ISSUE TITLE
レポート作成画面の実装

### ISSUE THREAD

**Issue by kinoshita0923** [NIT-Anan-Procon/procon33_RemoteTravelers_app#15]
## 概要
写真を撮った後に遷移するレポート作成画面を実装する

## 具体的にやること

- [x] #19
- [x] #25
- [x] #30
- [x] #38
- [x] #47
- [x] #56

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/7eHbwS6kRyybebRecWNSiY/RemoteTravelers?node-id=139%3A171

## ゴール・目的（完成物の定義）
旅レポートをDBに追加することができる。

**Comment by Mitsuki4123** [comment]
タスク終了に伴い閉じる
