### ISSUE TITLE
レポートを閲覧する画面の作成

### ISSUE THREAD

**Issue by kinoshita0923** [NIT-Anan-Procon/procon33_RemoteTravelers_app#16]
## 概要
メイン画面で表示されているレポートをクリックするとレポートの詳細を見ることができる画面を作成する。

## 具体的にやること

- [x] #20
- [ ] メイン画面から遷移する処理(`report_id`を受け渡す)
- [ ] `ViewReportActivity`にボタンや入力欄などを配置する
- [ ] `ViewReportActivity`で受け取った`report_id`でレポートについてのデータを取得し、表示する
- [ ] 戻るボタンを押すとメイン画面に遷移する処理を作成

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/7eHbwS6kRyybebRecWNSiY/RemoteTravelers?node-id=131%3A102

## ゴール・目的（完成物の定義）
レポートの詳細を確認することができる。

**Comment by Mitsuki4123** [comment]
別issueで対応済み
