### ISSUE TITLE
ピンの見た目を変更

### ISSUE THREAD

**Issue by KubotaShunsuke** [NIT-Anan-Procon/procon33_RemoteTravelers_app#55]
## 概要
ピンの見た目を変更する。

## 具体的にやること

- [ ] 旅行者の現在地を表示するピンの見た目を変更する
- [ ] 行先提案機能のピンの見た目を変更する

## FigmaのURL または UIの画像(あれば)

![newPin](https://user-images.githubusercontent.com/86040436/188303767-0f5ca468-0404-4f83-9693-5fc738e94988.jpg)

## ゴール・目的（完成物の定義）
全てのピンの見た目を変更する。

**Comment by kubo-shuns** [comment]
みにくい気がするのでやめました
