### ISSUE TITLE
旅行開始・終了機能の実装

### ISSUE THREAD

**Issue by KubotaShunsuke** [NIT-Anan-Procon/procon33_RemoteTravelers_app#80]
## 概要
旅行開始・終了機能の実装

## 具体的にやること

- [x] #85
- [x] #93
- [x] #102
- [ ] #103

## FigmaのURL または UIの画像(あれば)
なし
## ゴール・目的（完成物の定義）
旅行開始・終了機能の実装

**Comment by Mitsuki4123** [comment]
issue103は実装予定にないので終了とします
