### ISSUE TITLE
commentActivityとして分ける

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon33_RemoteTravelers_app#81]
## 概要
commentActivityを作成しまとめる

## 具体的にやること

- [ ] commentActivityを作成
- [ ] コメント機能が問題なく使える

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/7eHbwS6kRyybebRecWNSiY/RemoteTravelers?node-id=0%3A1
## ゴール・目的（完成物の定義）
commentActivityを作成しまとめられる

**Comment by KubotaShunsuke** [comment]
Buttonなどを触っているのでActivityで分けずに実装することになった
