### ISSUE TITLE
旅レポートを表示する機能の実装

### ISSUE THREAD

**Issue by KubotaShunsuke** [NIT-Anan-Procon/procon33_RemoteTravelers_app#92]
## 概要
旅レポートを表示する機能を実装

## 具体的にやること

- [x] #95
- [x] #116

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/7eHbwS6kRyybebRecWNSiY/RemoteTravelers?node-id=0%3A1
## ゴール・目的（完成物の定義）
旅レポートを表示する機能を実装

**Comment by Mitsuki4123** [comment]
タスク終了のため閉じる
