### ISSUE TITLE
旅アルバムを実装する

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon33_RemoteTravelers_app#99]
## 概要
旅アルバムを実装する

## 具体的にやること

- [x] #105
- [x] #110
- [x] #112
- [ ] 緯度と経度から地名(県と市までの予定)を取得する
- [x] #114

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/7eHbwS6kRyybebRecWNSiY/RemoteTravelers?node-id=393%3A70

## ゴール・目的（完成物の定義）
旅アルバムの実装を完了する

**Comment by Mitsuki4123** [comment]
実装予定の機能は実現したため閉じる
